Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,6 +31,14 @@ jobs:
           image: bookworm
           output:
             "results/"
+      - name: Show Orca Scan Results in Logs
+        run: |
+          echo "===== Orca image.json ====="
+          cat results/image.json || echo "image.json not found"
+
+          echo "===== Orca image directory listing ====="
+          ls -R results/image || echo "results/image directory not found"
+
       - name: Upload Orca Scan Results
         uses: actions/upload-artifact@v4
         with:
